### ISSUE TITLE
Use existing python installation

### ISSUE THREAD

**Issue by pasn** [zooba/vsts-python-tasks#6]
I would like to have an option to use existing python installation on the agent instead of installing it every time.

Hosted VS2017 agents have python 3.6.x and 2.x installed. The first one is said to be installed in the $PATH. The issue I have is that I cannot use "Execute python script" task as it requires "python search root" parameter to be fiiled. I tried to pass $PATH variable here but this task is currently unable to parse paths separated by ';' sign. Maybe you could add an option to use $PATH instead of searching for installations?

**Comment by zooba** [comment]
All of the tasks have been updated to work with the built-in "Use Python version" task (which is not part of my extension). So they all only run once now, and you should use multi-configuration settings to run multiple versions, and the "Install" task now updates PATH.

If you don't see the updates, make sure you select the latest version for each task from the dropdown when editing your definition. They won't automatically upgrade, because it may break your builds.
